default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: postgres
  host: localhost
  port: 5433  # Confirme se esta é a porta correta
  password:

development:
  <<: *default
  database: rails_websocket_development

test:
  <<: *default
  database: rails_websocket_test

production:
  primary: &primary_production
    <<: *default
    database: rails_websocket_production
    username: rails_websocket
    password: <%= ENV["RAILS_WEBSOCKET_DATABASE_PASSWORD"] %>

  cache:
    <<: *primary_production
    database: rails_websocket_production_cache
    migrations_paths: db/cache_migrate

  queue:
    <<: *primary_production
    database: rails_websocket_production_queue
    migrations_paths: db/queue_migrate

  cable:
    <<: *primary_production
    database: rails_websocket_production_cable
    migrations_paths: db/cable_migrate
